### ISSUE TITLE
Error: indent/outdent mismatch

### ISSUE THREAD

**Issue by jschleus** [bemeurer/beautysh#29]
First: I'm very happy to find a bash beautifier. But for one of my scripts it fails with
```
error: indent/outdent mismatch: 1.
```
although I (and also "shellcheck") didn't find an error.

After some trail and error attempts I could reduce the problem to the following command using command substitution
```
T=$(echo "\"a\"")
```
But for e.g. putting a space before the right parenthesis let beautish work without an error!

**Comment by f18m** [comment]
I also found this error; in my case I found it's caused by the following snippet:

`
function mytest()
{
    local re='^[\-]?[[0-9]+$'
		echo "hello world"
}
`

**Comment by f18m** [comment]
Also this kind of code is producing the same indent/outdent mismatch error:

```
function mytest2()
{
    RESTORE="$(echo -en '\033[0m')"
	echo "hello world"
}
```

**Comment by bemeurer** [comment]
@f18m Can this be closed?

**Comment by bemeurer** [comment]
I just verified that this is fixed!

**Comment by jschleus** [comment]
I just want to confirm that the bug is fixed.

Sorry, I had have overseen it since I found no response here and after a quick look on the source of version 3.12 I had the wrong impression that the mentioned problem wasn't yet fixed.  But it was, great!

**Comment by thpryrchn** [comment]
I am still getting this error!! Would be nice if the error show where it happens, like how python does when it hits an error...
Here is my code that is tripping it up!
```bash
#!/bin/bash

if [[ $ext = "mov" ]]; then
    echo "ffmpeg -i \"$infile\" $ffextra1 $ffextra -metadata xmp=\"\" -c:v prores -c:a pcm_s24le -metadata:s:v:0 encoder='Apple ProRes 422' -metadata language=eng -vf $vf -aspect $aspect -y -loglevel verbose -movflags +faststart \"$outfile\""
    sleep 5
    ffmpeg -i "$infile" $ffextra1 $ffextra -metadata xmp="" -c:v prores -c:a pcm_s24le -metadata:s:v:0 encoder='Apple ProRes 422' -metadata language=eng -vf "$vf" -aspect $aspect -y -loglevel verbose "$outfile"
else
    echo "ffmpeg -i $infile $ffextra1 $ffextra -metadata xmp="" -vf $vf -y -pix_fmt yuv420p -loglevel verbose -g $gop -maxrate:v $max -bufsize:v 30M -aspect $aspect -c:v libx264 -crf $crf -x264opts ref=4:qpmin=4:colorprim=bt709:transfer=bt709:colormatrix=bt709$x264ex -movflags +faststart $outfile"
    sleep 5
    ffmpeg -i "$infile" $ffextra1 $ffextra -metadata xmp="" -vf "$vf" -y -pix_fmt yuv420p -loglevel verbose -g $gop -maxrate:v "$max" -bufsize:v 30M -aspect $aspect -c:v libx264 -crf $crf -x264opts ref=4:qpmin=4:colorprim=bt709:transfer=bt709:colormatrix=bt709$x264ex -movflags +faststart "$outfile"
fi
done
say "Upres conversion finished!"
```
beautysh==6.0.1
